[package]
name = "briq_protocol"
version = "2.0.0"
cairo-version = "2.1.0-rc4"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo" }
# dojo_erc = { git = "https://github.com/dojoengine/dojo" }
dojo_erc = { path = "dojo-erc" }

[[target.dojo]]
build-external-contracts = [
    "briq_protocol::briq::BriqErc1155"
]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x03ee9e18edc71a6df30ac3aca2e0b02a198fbce19b7480a63a0d71cbd76652e0"
private_key = "0x0300001800000000300000180000000000030000000000003006001800006600"

keystore_password = "password"
keystore_path = "../keystore.json"
